### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by brunocalado** [CodeWringer/word-generator-foundryVTT#3]
Hi. 

I can't get it to work,

![image](https://user-images.githubusercontent.com/4999783/203563592-c0219087-0ca1-45e5-b451-e3c70db1e8a5.png)

**Comment by CodeWringer** [comment]
Hey there, thanks for reporting! 

I'll also need the following information to help:
1. What browser are you using?
2. What version of that browser?
3. What version of FoundryVTT was this tested on?

**Comment by CodeWringer** [comment]
I'm a dummy and forgot to add required Handlebars helper functions. 

This issue will be resolved with the next release.

**Comment by brunocalado** [comment]
I don't know what is Handlebars. But,tks
